### ISSUE TITLE
修改hidden_num为1024或者256都会报错tensor 不匹配

### ISSUE THREAD

**Issue by tianyuso** [saiwaiyanyu/bi-lstm-crf-ner-tf2.0#13]
hidden_num从512修改为1024后,
报错:
[-INFO-] 2021-01-21 16:53:14,307 20534  train.<module> line:32  hidden_num:1024, vocab_size:4733, label_size:14
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    loss, logits, text_lens = train_one_step(text_batch, labels_batch)
  File "train.py", line 47, in train_one_step
    logits, text_lens, log_likelihood = model(text_batch, labels_batch,training=True)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 968, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)
  File "/mnt/python/tensorflow2/bi-lstm-crf-ner-tf2.0/model.py", line 35, in call
    logits = self.dense(self.biLSTM(inputs))
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 531, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 964, in __call__
    self._maybe_build(inputs)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/layers/wrappers.py", line 685, in build
    self.forward_layer.build(input_shape)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 573, in build
    self.cell.build(step_input_shape)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 316, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 2324, in build
    caching_device=default_caching_device)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 577, in add_weight
    caching_device=caching_device)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 724, in _add_variable_with_custom_getter
    name=name, shape=shape)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 791, in _preload_simple_restoration
    checkpoint_position=checkpoint_position, shape=shape)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 75, in __init__
    self.wrapped_value.set_shape(shape)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1107, in set_shape
    (self.shape, shape))
ValueError: Tensor's shape (300, 2048) is not compatible with supplied shape (300, 4096)

这个输出维度,应该是可以自己定义的吧?

**Comment by tianyuso** [comment]
已解决
