### ISSUE TITLE
trainer error

### ISSUE THREAD

**Issue by shfshf** [saiwaiyanyu/bi-lstm-crf-ner-tf2.0#3]
总是报这个错，很奇怪
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/ner_tf2/lib/python3.6/logging/config.py", line 565, in configure
    handler = self.configure_handler(handlers[name])
  File "/Applications/anaconda3/envs/ner_tf2/lib/python3.6/logging/config.py", line 738, in configure_handler
    result = factory(**kwargs)
  File "/Applications/anaconda3/envs/ner_tf2/lib/python3.6/logging/handlers.py", line 202, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/Applications/anaconda3/envs/ner_tf2/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Applications/anaconda3/envs/ner_tf2/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Applications/anaconda3/envs/ner_tf2/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shf/PycharmProjects/bi-lstm-crf-ner-tf2.0/log/error.log'

**Comment by saiwaiyanyu** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/Users/shf/PycharmProjects/bi-lstm-crf-ner-tf2.0/log/error.log'

你好，需要在路径下创建一个 log  目录哈。

**Comment by shfshf** [comment]
ok，谢谢了
